print("OK Now for the final example")
print("How about importing some libraries?")
print("Trust me, its not that bad. If you got here from my Instructables, you already have imported libraries (libs)")
print("Here we go. The commands below me will import the time lib!")
import time
print("done! That wasn't bad!")
print("Lets try using the time lib. This command will ONLY work if you have the time lib imported!")
print("the time lib has many functions. a common was is wait. It can be used like this: 'time.sleep(5)'")
print("This command will make the application wait for 5 seconds! Lets try using it!")
input("Press enter when you finished reading!")
print()
print("This message comes first.")
time.sleep(2)
print("this message came 2 seconds later...")
time.sleep(4)
print("This message came 4 seconds after the message above, and 6 seconds after the first message!! So neat!")
